name: publish

on:
  push:
    branches: [master]

  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1  # Using the latest version
        with:
          ref: refs/heads/release
          
      - name: Layout file name
        id: naming
        env:
          GIT_HASH: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
          GIT_REF: ${{ github.ref_name }}
          GIT_REF_TYPE: ${{ github.ref_type }}
          GITHUB_ACTION_EVENT_NAME: ${{ github.event_name }}
        run: |
         CUR_DATE_TIME=$(date +'%Y-%m-%d')
         echo "output_name=Adonis_Master_${CUR_DATE_TIME}_$(git rev-parse --short "$GIT_HASH")" >> $GITHUB_OUTPUT
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Standalone
        run: rojo build -o ${{ steps.naming.outputs.output_name }}.rbxm .github/build.project.json
     
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ steps.naming.outputs.output_name }}
          path: ${{ steps.naming.outputs.output_name }}.rbxm
        
      - name: Build MainModule
        run: rojo build -o Adonis_MainModule.rbxm .github/module.deploy.project.json
        
      - name: Publish Module
        run: |
          curl --location --request PATCH 'https://apis.roblox.com/assets/v1/assets/${{ secrets.MODULE_ID }}' \
          --header 'x-api-key: ${{ secrets.ROBLOX_API_KEY }}' \
          --form 'request={
            "assetType": "Model",
            "assetId": "${{ secrets.MODULE_ID }}"
          }' \
          --form 'fileContent=@Adonis_MainModule.rbxm;type=model/x-rbxm'
